module.exports = [
  {
    description: "ACH Transfer from 42313777",
    amount: 7000,
    date: "2023-06-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Income",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "ACH Transfer from 42313777",
    amount: 7000,
    date: "2023-07-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Income",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "ACH Transfer from 42313777",
    amount: 7000,
    date: "2023-08-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Income",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "ACH Transfer from 421545888",
    amount: 5000,
    date: "2023-08-09",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Income",
    userEmail: "john.smith@email.com"
  },
  {
    description: "ACH Transfer from 421545888",
    amount: 5000,
    date: "2023-07-09",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Income",
    userEmail: "john.smith@email.com"
  },
  {
    description: "ACH Transfer from 421545888",
    amount: 5000,
    date: "2023-06-09",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Income",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Fund Deposit",
    amount: 20000,
    date: "2023-06-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Fund",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Fund Deposit",
    amount: 40000,
    date: "2023-06-02",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Fund",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Payment",
    amount: 300,
    date: "2023-06-31",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Fund",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Payment",
    amount: 1000,
    date: "2023-07-31",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Fund",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Fund Deposit",
    amount: 5000,
    date: "2023-06-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Fund",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Fund Deposit",
    amount: 10000,
    date: "2023-06-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Fund",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Payment",
    amount: 1000,
    date: "2023-06-31",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Fund",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Payment",
    amount: 2000,
    date: "2023-07-31",
    categoryId: 1,
    userId: 1,
    creditDebit: "debit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Fund",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "UBER EATS",
    amount: -87,
    date: "2023-08-15",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Starbucks",
    amount: -5,
    date: "2023-08-12",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Gas Station",
    amount: -35,
    date: "2023-08-10",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Car",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Rent Payment",
    amount: -1000,
    date: "2023-08-09",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Rent/Mortgage",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Movie Ticket",
    amount: -15,
    date: "2023-08-08",
    categoryId: 5,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Activities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Grocery Shopping",
    amount: -70,
    date: "2023-08-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Online Shopping",
    amount: -150,
    date: "2023-08-03",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Amazon Purchase",
    amount: -50,
    date: "2023-08-01",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Utility Bill",
    amount: -120,
    date: "2023-07-28",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Utilities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Streaming Service",
    amount: -10,
    date: "2023-07-25",
    categoryId: 5,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Streaming",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Dinner at Restaurant",
    amount: -40,
    date: "2023-07-22",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Restaurant",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Clothing Store",
    amount: -80,
    date: "2023-07-20",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Gas Refill",
    amount: -25,
    date: "2023-07-17",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Car",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Online Shopping",
    amount: -120,
    date: "2023-07-15",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Electric Bill",
    amount: -80,
    date: "2023-07-12",
    categoryId: 5,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Utilities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Grocery Shopping",
    amount: -60,
    date: "2023-07-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Shopping Spree",
    amount: -150.75,
    date: "2023-08-15",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Coffee Break",
    amount: -5.25,
    date: "2023-08-17",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341234",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Lunch with Friends",
    amount: -22.0,
    date: "2023-06-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Restaurant",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Groceries",
    amount: -65.0,
    date: "2023-06-15",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Coffee Break",
    amount: -5.0,
    date: "2023-06-20",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Shopping Spree",
    amount: -98.5,
    date: "2023-08-10",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Coffee Break",
    amount: -3.5,
    date: "2023-08-15",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Dinner with Friends",
    amount: -40.0,
    date: "2023-06-25",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Restaurant",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Groceries",
    amount: -60.0,
    date: "2023-07-02",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Coffee Break",
    amount: -4.25,
    date: "2023-07-10",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Shopping Spree",
    amount: -105.75,
    date: "2023-08-05",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Coffee Break",
    amount: -3.75,
    date: "2023-08-12",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341251",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Dinner at Restaurant",
    amount: -45.0,
    date: "2023-06-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Restaurant",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Grocery Shopping",
    amount: -78.5,
    date: "2023-06-10",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Coffee Break",
    amount: -4.25,
    date: "2023-06-15",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Rent Payment",
    amount: -1300.0,
    date: "2023-06-20",
    categoryId: 6,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Rent/Mortgage",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Car Insurance",
    amount: -150.0,
    date: "2023-06-25",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Insurance",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Utility Bill",
    amount: -95.0,
    date: "2023-07-01",
    categoryId: 9,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Utilities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Movie Ticket",
    amount: -12.5,
    date: "2023-07-05",
    categoryId: 10,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Activities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Clothing Shopping",
    amount: -65.75,
    date: "2023-07-10",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Streaming Subscription",
    amount: -8.99,
    date: "2023-07-15",
    categoryId: 11,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Streaming",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "Outdoor Activities",
    amount: -20.0,
    date: "2023-07-20",
    categoryId: 12,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Activities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "CASH APP",
    amount: -50.0,
    date: "2023-06-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Restaurant",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "PIXIESETCOM",
    amount: -15.0,
    date: "2023-06-10",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "BP* PETROLEUM",
    amount: -30.0,
    date: "2023-06-15",
    categoryId: 7,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Car",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "AMZN MKTP",
    amount: -120.0,
    date: "2023-06-20",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Clothing",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "CVS",
    amount: -25.5,
    date: "2023-06-25",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Grocery",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "UBER EATS",
    amount: -40.0,
    date: "2023-07-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Restaurant",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "COMPASS COFFEE",
    amount: -6.75,
    date: "2023-07-05",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Coffee Shops",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "COMCAST 800-COMCAST",
    amount: -60.0,
    date: "2023-07-10",
    categoryId: 9,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Utilities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "PEPCO",
    amount: -85.0,
    date: "2023-07-15",
    categoryId: 9,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Utilities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "METRO",
    amount: -4.75,
    date: "2023-07-20",
    categoryId: 12,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123415771",
    categoryName: "Activities",
    userEmail: "avery.liv@email.com"
  },
  {
    description: "CASH APP",
    amount: -50.0,
    date: "2023-06-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Restaurant",
    userEmail: "john.smith@email.com"
  },
  {
    description: "PIXIESETCOM",
    amount: -15.0,
    date: "2023-06-10",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Grocery",
    userEmail: "john.smith@email.com"
  },
  {
    description: "BP* PETROLEUM",
    amount: -30.0,
    date: "2023-06-15",
    categoryId: 7,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "AMZN MKTP",
    amount: -120.0,
    date: "2023-06-20",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Clothing",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CVS",
    amount: -25.5,
    date: "2023-06-25",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Grocery",
    userEmail: "john.smith@email.com"
  },
  {
    description: "UBER EATS",
    amount: -40.0,
    date: "2023-07-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Restaurant",
    userEmail: "john.smith@email.com"
  },
  {
    description: "COMPASS COFFEE",
    amount: -6.75,
    date: "2023-07-05",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "COMCAST 800-COMCAST",
    amount: -60.0,
    date: "2023-07-10",
    categoryId: 9,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Utilities",
    userEmail: "john.smith@email.com"
  },
  {
    description: "PEPCO",
    amount: -85.0,
    date: "2023-07-15",
    categoryId: 9,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Utilities",
    userEmail: "john.smith@email.com"
  },
  {
    description: "METRO",
    amount: -4.75,
    date: "2023-07-20",
    categoryId: 12,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Activities",
    userEmail: "john.smith@email.com"
  },
  {
    description: "SPRINT*NEXTEL",
    amount: -75.0,
    date: "2023-06-05",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "STARBUCKS",
    amount: -5.25,
    date: "2023-06-10",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CRUMPASS COFFEE",
    amount: -4.5,
    date: "2023-06-15",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "MCDONALDS",
    amount: -8.75,
    date: "2023-06-20",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Restaurant",
    userEmail: "john.smith@email.com"
  },
  {
    description: "KROEGER FOODS",
    amount: -45.2,
    date: "2023-06-25",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Grocery",
    userEmail: "john.smith@email.com"
  },
  {
    description: "TARGET.COM",
    amount: -120.0,
    date: "2023-07-01",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Clothing",
    userEmail: "john.smith@email.com"
  },
  {
    description: "APPLE.COM",
    amount: -750.0,
    date: "2023-07-05",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Jewelry",
    userEmail: "john.smith@email.com"
  },
  {
    description: "GEICO INSUR",
    amount: -185.5,
    date: "2023-07-10",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CAPITOL ONE INSURASE",
    amount: -210.0,
    date: "2023-07-15",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Sprint Payment",
    amount: -65.0,
    date: "2023-07-20",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12343232",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "SPRINT*NEXTEL",
    amount: -65.5,
    date: "2023-06-02",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "STARBUCKS",
    amount: -4.75,
    date: "2023-06-04",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CRUMPASS COFFEE",
    amount: -5.25,
    date: "2023-06-06",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "MCDONALDS",
    amount: -8.0,
    date: "2023-06-08",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Restaurant",
    userEmail: "john.smith@email.com"
  },
  {
    description: "KROEGER FOODS",
    amount: -42.15,
    date: "2023-06-10",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Grocery",
    userEmail: "john.smith@email.com"
  },
  {
    description: "TARGET.COM",
    amount: -130.75,
    date: "2023-06-12",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Clothing",
    userEmail: "john.smith@email.com"
  },
  {
    description: "APPLE.COM",
    amount: -750.0,
    date: "2023-06-14",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Clothing",
    userEmail: "john.smith@email.com"
  },
  {
    description: "GEICO INSUR",
    amount: -185.5,
    date: "2023-06-16",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CAPITOL ONE INSURASE",
    amount: -215.0,
    date: "2023-06-18",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Sprint Payment",
    amount: -65.0,
    date: "2023-06-20",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "SPRINT*NEXTEL",
    amount: -65.5,
    date: "2023-08-01",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "STARBUCKS",
    amount: -4.75,
    date: "2023-08-02",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CRUMPASS COFFEE",
    amount: -5.25,
    date: "2023-08-03",
    categoryId: 3,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Coffee Shops",
    userEmail: "john.smith@email.com"
  },
  {
    description: "MCDONALDS",
    amount: -8.0,
    date: "2023-08-04",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Restaurant",
    userEmail: "john.smith@email.com"
  },
  {
    description: "KROEGER FOODS",
    amount: -42.15,
    date: "2023-08-05",
    categoryId: 2,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Grocery",
    userEmail: "john.smith@email.com"
  },
  {
    description: "TARGET.COM",
    amount: -130.75,
    date: "2023-08-06",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Clothing",
    userEmail: "john.smith@email.com"
  },
  {
    description: "APPLE.COM",
    amount: -750.0,
    date: "2023-08-07",
    categoryId: 4,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Clothing",
    userEmail: "john.smith@email.com"
  },
  {
    description: "GEICO INSUR",
    amount: -185.5,
    date: "2023-08-08",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "CAPITOL ONE INSURASE",
    amount: -215.0,
    date: "2023-08-09",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Sprint Payment",
    amount: -65.0,
    date: "2023-08-10",
    categoryId: 8,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "12341144",
    categoryName: "Car",
    userEmail: "john.smith@email.com"
  },
  {
    description: "Starbucks Coffee",
    amount: -12.5,
    date: "2023-08-03",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Coffee Shops",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Grocery Store XYZ",
    amount: -127.45,
    date: "2023-08-04",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Grocery",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Netflix Subscription",
    amount: -15.99,
    date: "2023-08-02",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Restaurant Bill",
    amount: -65.3,
    date: "2023-08-08",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Restaurant",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Online Clothing Store",
    amount: -97.1,
    date: "2023-08-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Clothing",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Apple iTunes Store",
    amount: -14.2,
    date: "2023-08-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Gas Station ABC",
    amount: -32.12,
    date: "2023-08-13",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Car",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Hotel Reservation",
    amount: -150.75,
    date: "2023-08-07",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Jewelry Store Transaction",
    amount: -212.65,
    date: "2023-08-11",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Jewelry",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Utility Bill Payment",
    amount: -78.5,
    date: "2023-08-16",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Utilities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Fast Food Restaurant",
    amount: -23.89,
    date: "2023-08-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Restaurant",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Online Gaming Purchase",
    amount: -49.99,
    date: "2023-08-09",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Furniture Store Purchase",
    amount: -320.45,
    date: "2023-08-06",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Rent/Mortgage",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Airline Ticket Booking",
    amount: -450.3,
    date: "2023-08-12",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Amazon Purchase",
    amount: -78.25,
    date: "2023-08-14",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Clothing",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Gym Membership",
    amount: -45.0,
    date: "2023-08-02",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Electronics Store Purchase",
    amount: -215.75,
    date: "2023-08-07",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Electronics",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Pharmacy Prescription",
    amount: -25.45,
    date: "2023-08-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Utilities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Entertainment Venue Tickets",
    amount: -75.0,
    date: "2023-08-15",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Health & Wellness Services",
    amount: -89.99,
    date: "2023-08-12",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Starbucks Coffee",
    amount: -7.5,
    date: "2023-06-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Coffee Shops",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Grocery Store XYZ",
    amount: -110.35,
    date: "2023-06-08",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Grocery",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Netflix Subscription",
    amount: -15.99,
    date: "2023-06-10",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Restaurant Bill",
    amount: -55.2,
    date: "2023-06-12",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Restaurant",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Online Clothing Store",
    amount: -80.15,
    date: "2023-06-15",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Clothing",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Apple iTunes Store",
    amount: -10.5,
    date: "2023-06-18",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Gas Station ABC",
    amount: -28.1,
    date: "2023-06-20",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Car",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Hotel Reservation",
    amount: -140.6,
    date: "2023-06-22",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Jewelry Store Transaction",
    amount: -205.75,
    date: "2023-06-25",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Jewelry",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Utility Bill Payment",
    amount: -70.4,
    date: "2023-06-28",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Utilities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Fast Food Restaurant",
    amount: -20.85,
    date: "2023-06-30",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Restaurant",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Online Gaming Purchase",
    amount: -45.99,
    date: "2023-07-02",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Furniture Store Purchase",
    amount: -305.2,
    date: "2023-07-05",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Rent/Mortgage",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Online Marketplace Purchase",
    amount: -65.5,
    date: "2023-07-07",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Amazon Purchase",
    amount: -120.0,
    date: "2023-07-09",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Clothing",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Uber Ride",
    amount: -25.15,
    date: "2023-07-11",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Car",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Airline Ticket Booking",
    amount: -450.9,
    date: "2023-07-13",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Subscription Service XYZ",
    amount: -12.99,
    date: "2023-07-15",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Electronics Store Purchase",
    amount: -299.5,
    date: "2023-07-17",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Electronics",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Pharmacy Prescription",
    amount: -45.25,
    date: "2023-07-19",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Insurance",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Car Rental",
    amount: -125.75,
    date: "2023-07-21",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Car",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Home Improvement Store",
    amount: -195.6,
    date: "2023-07-23",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Rent/Mortgage",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Gym Membership",
    amount: -40.0,
    date: "2023-07-25",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Electronics Subscription",
    amount: -10.99,
    date: "2023-07-27",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Electronics",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Charity Donation",
    amount: -50.0,
    date: "2023-07-29",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Utilities",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Music Store Purchase",
    amount: -65.75,
    date: "2023-07-31",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Streaming",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Coffee Shop Purchase",
    amount: -6.8,
    date: "2023-08-01",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Coffee Shops",
    userEmail: "emily.brown@email.com"
  },
  {
    description: "Entertainment Venue Tickets",
    amount: -70.2,
    date: "2023-08-02",
    categoryId: 1,
    userId: 1,
    creditDebit: "credit",
    accountId: 1,
    accountNumber: "123400012",
    categoryName: "Activities",
    userEmail: "emily.brown@email.com"
  }
];
